# Generated by Django 3.1.1 on 2020-10-08 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueboking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringes',
            options={},
        ),
    ]
