# Generated by Django 3.1.1 on 2020-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueboking', '0003_auto_20201008_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_details', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
